<?php
/**
 * @file
 * Theming page.
 * Task 1.1. Use custom_theme, theme_item_list, theme_fieldset, theme_table, include css.
 * Task 1.2. Use custom_theme with template and preprocess, theme_image, theme_item_list,
 *           theme_fieldset, theme_table, include css.
 */

/**
 * Implements hook_menu().
 */
function round_two_menu() {
  $items['round-two/task-1-1'] = array(
    'title' => 'Round 2. Task 1.1.',
    'page callback' => 'round_two_page_task1',
    'access arguments' => array('access content'),
  );
  $items['round-two/task-1-2'] = array(
    'title' => 'Round 2. Task 1.2.',
    'page callback' => 'round_two_page_task2',
    'access arguments' => array('access content'),
  );
  return $items;
}

/**
 * The page callback for task 1.1.
 */
function round_two_page_task1() {
  $title = t('Round 2');
  $items = round_two_build_array_items();
  //for our theme. Also, will add round_two.css
  $build['our_theme'] = array(
    '#theme' => 'round_two_theming_custom',
    '#attached' => array('css' => array(drupal_get_path('module', 'round_two') . '/round_two.css')),
    '#title' => $title,
    '#items' => $items,
  );
  return $build;
}

/**
 * build array for round_two_page_task1
 * @return array
 */
function round_two_build_array_items() {
  $arr = array(
    t('one'),
    t('two'),
    t('three'),
    t('four'),
    t('five'),
    t('six'),
  );
  return $arr;
}

/**
 * Implements hook_theme().
 */
function round_two_theme() {
  return array(
    'round_two_theming_custom' => array(
      'variables' => array(
        'title' => NULL,
        'items' => NULL,
      ),
    ),
    'round_two_theming_custom_with_template' => array(
      'variables' => array(
        'title' => NULL,
        'items' => NULL,
        'img_path' => NULL,
      ),
      'template' => 'round_two_with_img',
    ),
  );
}

/**
 * theming my custom page
 * @param $variables
 * @return string
 */
function theme_round_two_theming_custom($variables) {
  $title = $variables['title'];
  $items = $variables['items'];
  //build table
  $header = array(
    array('data' => $title . '<br/>' . t('Header 1')),
    array('data' => $title . '<br/>' . t('Header 2')),
    array('data' => $title . '<br/>' . t('Header 3'))
  );
  $type_list = array('ol', 'ul');
  for ($x = 0; $x++ < 6;) {
    $row = floor(($x - 1) / 3);
    //build cell with item_list of different classes
    $var = array(
      'items' => $items,
      'title' => 'List ' . $items[$x - 1],
      'type' => $type_list[$row],
      'attributes' => array('class' => 'round-two-list' . $x),
    );
    $rows[$row][] = array('data' => theme('item_list', $var));
  }
  $output = theme('table', array('header' => $header, 'rows' => $rows));

  //build fieldset
  drupal_add_library('system', 'drupal.collapse');
  $fieldset_element = array(
    '#title' => t('Round 2. Fieldset.'),
    '#children' => $output,
    '#collapsible' => TRUE,
    '#collapse' => TRUE,
    '#attributes' => array(
      'class' => array('collapsible', 'collapse')
    ),
  );
  $output = theme('fieldset', array('element' => $fieldset_element));
  return $output;
}

/**
 * The page callback for task 1.2.
 */
function round_two_page_task2() {
  $title = t('Round 2');
  $items = round_two_build_array_items();
  $img_path = drupal_get_path('module', 'round_two') . '/ladybird.png';
  $element_array = array(
    'title ' => $title,
    'items' => $items,
    'img_path' => $img_path,
  );
  $output = theme('round_two_theming_custom_with_template', $element_array);
  return $output;
}

/**
 * Implements hook_preprocess() for round_two_with_img.tpl.php.
 * @param $variables
 */
function round_two_preprocess_round_two_theming_custom_with_template(&$variables) {
  // created $variables['img']
  $image = array(
    'style_name' => 'Thumbnail',
    'path' => $variables['img_path'],
    'alt' => $variables['title'],
    'title' => $variables['title'],
    'width' => '100px',
    'hight' => '100px',
  );
  $img_html = theme('image', $image);
  $image_link = l($img_html, $variables['img_path'], array('html' => TRUE));
  $variables['img'] = $image_link;
  // created $variables['items']
  $for_theming_custom = array(
    'title' => $variables['title'],
    'items' => $variables['items'],
  );
  $variables['items'] = theme('round_two_theming_custom', $for_theming_custom);
  // add css
  drupal_add_css(drupal_get_path('module', 'round_two') . '/round_two.css');
}