<?php
/**
 * @file
 * Theming page.
 * Task 1. Use custom_theme, theme_item_list, theme_fieldset, theme_table, include css.
 */

/**
 * Implements hook_menu().
 */
function round_two_menu() {
  $items['round-two/task-1'] = array(
    'title' => 'Round 2. Task 1.',
    'page callback' => 'round_two_page_task1',
    'access arguments' => array('access content'),
  );
  return $items;
}

/**
 * The page callback.
 */
function round_two_page_task1() {
  $title = t('Round 2');
  $items = round_two_build_array_items();
  //for our theme. Also, will add round_two.css
  $build['our_theme'] = array(
    '#theme' => 'round_two_theming_custom',
    '#attached' => array('css' => array(drupal_get_path('module', 'round_two') . '/round_two.css')),
    '#title' => $title,
    '#items' => $items,
  );
  return $build;
}

/**
 * build array for round_two_page_task1
 * @return array
 */
function round_two_build_array_items() {
  $arr = array(
    t('one'),
    t('two'),
    t('three'),
    t('four'),
    t('five'),
    t('six'),
  );
  return $arr;
}

/**
 * Implements hook_theme().
 */
function round_two_theme() {
  return array(
    'round_two_theming_custom' => array(
      'variables' => array(
        'title' => NULL,
        'items' => NULL,
      ),
    ),
  );
}

/**
 * theming my custom page
 * @param $variables
 * @return string
 */
function theme_round_two_theming_custom($variables) {
  $title = $variables['title'];
  $items = $variables['items'];
  //build table
  $header = array(
    array('data' => $title . '<br/>' . t('Header 1')),
    array('data' => $title . '<br/>' . t('Header 2')),
    array('data' => $title . '<br/>' . t('Header 3'))
  );
  $type_list = array('ol', 'ul');
  for ($x = 0; $x++ < 6;) {
    $row = floor(($x - 1) / 3);
    //build cell with item_list of different classes
    $var = array(
      'items' => $items,
      'title' => 'List ' . $items[$x - 1],
      'type' => $type_list[$row],
      'attributes' => array('class' => 'round-two-list' . $x),
    );
    $rows[$row][] = array('data' => theme('item_list', $var));
  }
  $output = theme('table', array('header' => $header, 'rows' => $rows));

  //build fieldset
  drupal_add_library('system', 'drupal.collapse');
  $fieldset_element = array(
    '#title' => t('Round 2. Fieldset.'),
    '#children' => $output,
    '#collapsible' => TRUE,
    '#collapse' => TRUE,
    '#attributes' => array(
      'class' => array('collapsible', 'collapse')
    ),
  );
  $output = theme('fieldset', array('element' => $fieldset_element));
  return $output;
}